In [2]:
!pip install lightgbm

Looking in indexes: http://mirrors.tencentyun.com/pypi/simple
     |████████████████████████████████| 1.2 MB 865 kB/s eta 0:00:01


In [2]:
!pip install joblib

Looking in indexes: http://mirrors.tencentyun.com/pypi/simple


In [9]:
import pandas as pd
import numpy as np
import lightgbm as lgb
import gc
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.preprocessing import StandardScaler
import joblib
np.random.seed(2020)

def nn_model_age(train_x, test_x,train_y, test_y):
#     model = MLPClassifier(hidden_layer_sizes = (600,400,10),
#                           learning_rate = 'adaptive',
#                         learning_rate_init = 1,
# #                         early_stopping=True,
#                         max_iter=10000,
#                         verbose=10)
#     model.fit(train_x, train_y)
    model = joblib.load('w2v_nn_age_1.pkl')
#     
#     joblib.dump(model, 'w2v_nn_age_1.pkl')
    
    y_t_pred = model.predict(test_x)
    
    # print(model.get_score(importance_type='weight'))
    cm = confusion_matrix(test_y, y_t_pred)
    np.set_printoptions(precision=3)                                    # 显示精度
    cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]  # 将样本矩阵转化为比率

    print('age************************************')
    print('confusion_matrix is \n {:} \n '.format(cm_normalized))
    print('test acc is \n {:} \n '.format(np.sum(test_y==y_t_pred)/len(test_y)))
    print(classification_report(test_y,y_t_pred))
    print('accuracy is %f , sen is %f,spe is %f ' % (accuracy_score(test_y, y_t_pred) * 100,
                                                     cm_normalized[0][0],cm_normalized[1][1] ))

    return accuracy_score(test_y, y_t_pred)

def nn_model_gender(train_x, test_x,train_y, test_y):
#     model = MLPClassifier(hidden_layer_sizes = (600,400,2),
#                           learning_rate = 'adaptive',
#                         learning_rate_init = 1,
# #                         early_stopping=True,
#                         max_iter=10000,
#                         verbose=10)
#     model.fit(train_x, train_y)
    
    model = joblib.load('w2v_nn_age_1.pkl')
    
#     joblib.dump(model, 'w2v_nn_gender_1.pkl')
    
    y_t_pred = model.predict(test_x)
    
    # print(model.get_score(importance_type='weight'))
    cm = confusion_matrix(test_y, y_t_pred)
    np.set_printoptions(precision=3)                                    # 显示精度
    cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]  # 将样本矩阵转化为比率

    print('age************************************')
    print('confusion_matrix is \n {:} \n '.format(cm_normalized))
    print('test acc is \n {:} \n '.format(np.sum(test_y==y_t_pred)/len(test_y)))
    print(classification_report(test_y,y_t_pred))
    print('accuracy is %f , sen is %f,spe is %f ' % (accuracy_score(test_y, y_t_pred) * 100,
                                                     cm_normalized[0][0],cm_normalized[1][1] ))

    return accuracy_score(test_y, y_t_pred)

def load_data():
    # user
    data = pd.read_csv('../w2v_feat_data/train_data.csv')
    label = data[['age','gender']]
    
    data = data.drop(['user_id','age','gender'],axis = 1)
    return data,label

In [2]:
data,label = load_data()

In [6]:
#划分age的训练和测试数据
train_x, test_x, train_y, test_y = train_test_split(data, label, test_size=0.8,random_state=2020)

In [7]:
stand = StandardScaler()
stand.fit(train_x)
train_x,test_x = stand.transform(train_x),stand.transform(test_x)

In [10]:
# 训练模型
acc_age = nn_model_age(train_x, test_x,train_y['age'], test_y['age'])
acc_gender = nn_model_gender(train_x, test_x,train_y['gender'], test_y['gender'])

age************************************
confusion_matrix is 
 [[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]] 
 
test acc is 
 0.22575555555555554 
 


/opt/conda/envs/python3/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           1       0.00      0.00      0.00     28152
           2       0.00      0.00      0.00    119340
           3       0.23      1.00      0.37    162544
           4       0.00      0.00      0.00    120370
           5       0.00      0.00      0.00    104471
           6       0.00      0.00      0.00     81438
           7       0.00      0.00      0.00     53362
           8       0.00      0.00      0.00     25452
           9       0.00      0.00      0.00     15590
          10       0.00      0.00      0.00      9281

    accuracy                           0.23    720000
   macro avg       0.02      0.10      0.04    720000
weighted avg       0.05      0.23      0.08    720000

accuracy is 22.575556 , sen is 0.000000,spe is 0.000000 


/opt/conda/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:58: RuntimeWarning: invalid value encountered in true_divide


age************************************
confusion_matrix is 
 [[ 0.  0.  1.]
 [ 0.  0.  1.]
 [nan nan nan]] 
 
test acc is 
 0.0 
 


/opt/conda/envs/python3/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/envs/python3/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           1       0.00      0.00      0.00  482193.0
           2       0.00      0.00      0.00  237807.0
           3       0.00      0.00      0.00       0.0

    accuracy                           0.00  720000.0
   macro avg       0.00      0.00      0.00  720000.0
weighted avg       0.00      0.00      0.00  720000.0

accuracy is 0.000000 , sen is 0.000000,spe is 0.000000 
