In [2]:
!pip install keras

Looking in indexes: http://mirrors.tencentyun.com/pypi/simple
     |████████████████████████████████| 377 kB 835 kB/s eta 0:00:01     |██████████████████████████      | 307 kB 835 kB/s eta 0:00:01


In [1]:
from keras.models import Model
from keras.optimizers import SGD,Adam,RMSprop
# from keras.layers import Dense, Input, LSTM, Embedding,Dropout,Bidirectional,Flatten
from keras.layers import *
import os

# from __future__ import print_function
from keras import backend as K
from keras.engine.topology import Layer
import h5py

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import pandas as pd
import numpy as np
import keras

Using TensorFlow backend.


In [2]:
def data_load():
    print('loading data ... \n')
    with h5py.File('../../../get_w2v_feat/w2v1_pre_ad/word_test_ad_w2v_w200.h5', 'r') as f:
        data = np.array(f.get('word_data'))
    print('get data ... \n')
    return data

def load_data2():
    with h5py.File('../../../get_w2v_feat/w2v1_pre_advertiser/word_test_advertiser_w2v_w200.h5', 'r') as f:
        data = np.array(f.get('word_data'))
    return data
def load_data3():
    with h5py.File('../../../get_w2v_feat/w2v1_pre_creative_id/word_test_creative_w2v_w200.h5', 'r') as f:
        data = np.array(f.get('word_data'))
    return data

def load_data4():
    with h5py.File('../../../get_w2v_feat/w2v1_pre_industry/word_test_industry_w2v_w200.h5', 'r') as f:
        data = np.array(f.get('word_data'))
    return data
def load_data5():
    with h5py.File('../../../get_w2v_feat/w2v1_pre_product_id/word_test_product_id_w2v_w200.h5', 'r') as f:
        data = np.array(f.get('word_data'))
    return data

In [3]:
print('load data...')
data_ad = data_load()
data_advertiser = load_data2()
data_creative = load_data3()
data_industry = load_data4()
data_product_id = load_data5()


data_age = [data_ad,data_advertiser,data_creative]
data_gender = [data_ad,data_advertiser,data_creative,data_industry,data_product_id]

load data...
loading data ... 

get data ... 



In [4]:
del data_ad,data_advertiser,data_creative,data_industry,data_product_id

In [4]:

lstm_model_path_age1 = '../../../w2v_model5_lstm/lstm_comb/cross/cross_lstm32_comb_aver_age_adm_w200_1.309-0.461-001-1.375-0.434.hdf5'
model_age1 = keras.models.load_model(lstm_model_path_age1)
lstm_model_path_age2 = '../../../w2v_model5_lstm/lstm_comb/cross/cross_lstm32_comb_aver_age_adm_w200_1.311-0.458-001-1.375-0.434.hdf5'
model_age2 = keras.models.load_model(lstm_model_path_age2)
lstm_model_path_age3 = '../../../w2v_model5_lstm/lstm_comb/cross/cross_lstm32_comb_aver_age_adm_w200_1.312-0.460-001-1.375-0.434.hdf5'
model_age3 = keras.models.load_model(lstm_model_path_age3)
lstm_model_path_age4 = '../../../w2v_model5_lstm/lstm_comb/cross/cross_lstm32_comb_aver_age_adm_w200_1.314-0.461-001-1.374-0.434.hdf5'
model_age4 = keras.models.load_model(lstm_model_path_age4)
lstm_model_path_age5 = '../../../w2v_model5_lstm/lstm_comb/cross/cross_lstm32_comb_aver_age_adm_w200_1.322-0.454-001-1.377-0.433.hdf5'
model_age5 = keras.models.load_model(lstm_model_path_age5)

print('pre age ...')

probs_age1 = model_age1.predict(data_age, verbose=0)
probs_age2 = model_age2.predict(data_age, verbose=0)
probs_age3 = model_age3.predict(data_age, verbose=0)
probs_age4 = model_age4.predict(data_age, verbose=0)
probs_age5 = model_age5.predict(data_age, verbose=0)

pre_age = (probs_age1+probs_age2+probs_age3+probs_age4+probs_age5)/5

d_age = pd.DataFrame(pre_age)
d_age.to_csv('submission_age_pro.csv',index=False)

pre_age = np.reshape(np.argmax(pre_age, axis=1),[-1])
pre_age = pre_age + 1




Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



pre age ...


In [5]:
pre_age

array([3, 7, 2, ..., 2, 3, 5])

In [7]:
# 加载模型

lstm_model_path_gender1 = '../../../w2v_model5_lstm/lstm_comb/cross/cross_lstm32_comb_gender_w2v_200_pre_5in_0.165-0.942-001-0.178-0.936.hdf5'
model_gender1 = keras.models.load_model(lstm_model_path_gender1)
lstm_model_path_gender2 = '../../../w2v_model5_lstm/lstm_comb/cross/cross_lstm32_comb_gender_w2v_200_pre_5in_0.168-0.941-001-0.178-0.936.hdf5'
model_gender2 = keras.models.load_model(lstm_model_path_gender2)
lstm_model_path_gender3 = '../../../w2v_model5_lstm/lstm_comb/cross/cross_lstm32_comb_gender_w2v_200_pre_5in_0.169-0.940-001-0.177-0.936.hdf5'
model_gender3 = keras.models.load_model(lstm_model_path_gender3)
lstm_model_path_gender4 = '../../../w2v_model5_lstm/lstm_comb/cross/cross_lstm32_comb_gender_w2v_200_pre_5in_0.169-0.940-001-0.178-0.936.hdf5'
model_gender4 = keras.models.load_model(lstm_model_path_gender4)
lstm_model_path_gender5 = '../../../w2v_model5_lstm/lstm_comb/cross/cross_lstm32_comb_gender_w2v_200_pre_5in_0.170-0.939-001-0.177-0.936.hdf5'
model_gender5 = keras.models.load_model(lstm_model_path_gender5)
    
    
print('pre gender ...')

probs_gender1 = model_gender1.predict(data_gender, verbose=0)
probs_gender2 = model_gender2.predict(data_gender, verbose=0)
probs_gender3 = model_gender3.predict(data_gender, verbose=0)
probs_gender4 = model_gender4.predict(data_gender, verbose=0)
probs_gender5 = model_gender5.predict(data_gender, verbose=0)

pre_gender = (probs_gender1 + probs_gender2+probs_gender3+probs_gender4+probs_gender5)/5
d_gender = pd.DataFrame(pre_gender)
d_gender.to_csv('submission_gender_pro.csv',index=False)


pre_gender = np.array(pre_gender>0.5).astype('int')
pre_gender = pre_gender + 1




Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



pre gender ...


NameError: name 'probs_gender' is not defined

In [6]:

test_user_id = np.array(range(3000001,4000001))
res = pd.DataFrame(test_user_id)
res.columns = [['user_id']]

res['predicted_age']=pre_age
res['predicted_gender']=pre_gender
res.to_csv('submission.csv',index=False)

load data...
loading data ... 

get data ... 

pre age ...


NameError: name 'probs_age' is not defined

In [1]:
import pandas as pd
import numpy as np

In [2]:
attention_gender = pd.read_csv('../../../w2v_model5_lstm/attention_comb/summit_cross/submission_gender_pro.csv')

In [3]:
attention_submmit = pd.read_csv('../../../w2v_model5_lstm/attention_comb/summit_cross/submission.csv')

In [4]:
lstm_gender = pd.read_csv('submission_gender_pro.csv')

In [8]:
lstm_gender['0'].values

array([0.00784583, 0.99178535, 0.92472774, ..., 0.0091321 , 0.00423017,
       0.00576844])

In [9]:
attention_gender_pro = attention_gender['predicted_gender'].values
gender_pro = (attention_gender_pro + lstm_gender['0'].values)/2

gender_pre = np.array(gender_pro>0.5).astype('int')
gender_pre = gender_pre + 1

In [12]:
attention_submmit['predicted_gender'] = gender_pre

In [13]:
attention_submmit.to_csv('submission_add_gender.csv',index=False)

In [6]:
attention_age = pd.read_csv('../../../w2v_model5_lstm/attention_comb/summit_cross/submission_age_pro.csv')

In [7]:
lstm_age = pd.read_csv('../../../w2v_model5_lstm/lstm_comb/cross/submission_age_pro.csv')

In [8]:
submmit_pre = pd.read_csv('../../../w2v_model5_lstm/lstm_comb/cross/submmit_gender_add/submission.csv')

In [11]:
np.shape(attention_age.values)

(1000000, 10)

In [13]:
np.shape(lstm_age.values)

(1000000, 10)

In [15]:
age_pro_ = (attention_age.values + lstm_age.values)/2

In [16]:
age_pro_ = np.reshape(np.argmax(age_pro_, axis=1),[-1])
age_pro_ = age_pro_ + 1

In [17]:
age_pro_

array([3, 7, 4, ..., 2, 3, 5])

In [18]:
submmit_pre

user_id  predicted_age  predicted_gender
0       3000001              3                 1
1       3000002              7                 2
2       3000003              5                 2
3       3000004              3                 1
4       3000005              4                 1
...         ...            ...               ...
999995  3999996              3                 1
999996  3999997              2                 1
999997  3999998              2                 1
999998  3999999              3                 1
999999  4000000              5                 1

[1000000 rows x 3 columns]

In [19]:
submmit_pre['predicted_age'] = age_pro_

In [20]:
submmit_pre.to_csv('submission_add_gender_age.csv',index=False)